___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [2]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [13]:
my_list = [1,2,3]
my_list

[1, 2, 3]

* We can cast a normal Python List to an Numpy Array. This is 1-D Array

In [14]:
np.array(my_list)

array([1, 2, 3])

In [15]:
np.array([5,6,7])

array([5, 6, 7])

* We can get a matrix by casting list of lists to an Numpy Array. 2-D Array

* 2 sets of opening bracks on the array, you can see the array representation  [[ --> indicates 2-D array

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

* Useful for quickly generating an Array.

In [9]:
np.arange?

* arange() --> returns sequence of numbers. you can pass start, stop(exclusive), and step count

In [10]:
np.arange(0,10) # 1-D Array, Vector

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [17]:
np.array([np.arange(0,3), np.arange(3,6), np.arange(6,9)]) # 2-D array / Matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### zeros and ones

Generate arrays of zeros or ones

In [11]:
np.zeros(3)

array([ 0.,  0.,  0.])

* To get a 2-D array, you need to pass a tuple of the dimensions. (rows, columns)

In [18]:
np.zeros((5,5)) # pass the dimensions as a tuple

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [19]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [22]:
np.ones(3)

array([ 1.,  1.,  1.])

* You need to pass the dimensions as a Tuple

In [13]:
np.ones((3,4)) # pass the dimensions as a Tuple

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

### linspace
Return evenly spaced numbers over a specified interval.

* It returns a specified number of points(default 50) between an interval. 

* the below example, we are asking to return 50 points between 0 and 10
* It returns 1-D array of points **

In [20]:
np.linspace(0,10,3) # returns 1-D array of points

array([  0.,   5.,  10.])

In [15]:
np.linspace(0, 5, 10) # this is like saying, give me 10 evenly spaced numbers between 0 and 5. 

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [31]:
np.linspace(0,10,50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

## eye

Creates an identity matrix.

* Identity - eyeDentity
* It definitely a square matrix, so just give one dimension would be enough

In [21]:
np.eye(4) # all diagonal elements are of value 1

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand - uniform distribution over ``[0, 1)``
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [20]:
np.random.rand(2) # 1-D array of random samples between 0 and 1

array([ 0.08334465,  0.95479043])

In [21]:
np.random.rand(5)

array([ 0.56483655,  0.58007021,  0.438505  ,  0.62958846,  0.97809687])

* Create a 2-D array of dimensions 5x5 with random samples (these random samples are between 0 and 1

* Pass in the dimensions are arguments, no need of passing as a tuple

In [22]:
np.random.rand(5,5) # 2-D array of random samples between 0 and 1

array([[ 0.4407016 ,  0.94760364,  0.13065799,  0.31258092,  0.53407632],
       [ 0.28055339,  0.44051138,  0.99813294,  0.90144591,  0.99051125],
       [ 0.64871891,  0.29302105,  0.43181632,  0.91864521,  0.09955653],
       [ 0.5511491 ,  0.3525472 ,  0.30259851,  0.31872568,  0.93056619],
       [ 0.56461251,  0.18273753,  0.32205174,  0.30859142,  0.8659296 ]])

### randn

Return a sample (or samples) from the "standard normal" or Gaussean distribution centered around zero. Unlike rand which is uniform:

* What I observed is, it includes both negative and positive samples

In [18]:
np.random.randn(2)

array([ 0.81099504, -1.08237942])

In [19]:
np.random.randn(5)

array([ 0.25404177,  0.10820521, -0.36122814,  0.50970285, -0.25530513])

In [45]:
np.random.randn(5,5) # 2-D matrix or array of random samples from normal distribution.

array([[ 0.70154515,  0.22441999,  1.33563186,  0.82872577, -0.28247509],
       [ 0.64489788,  0.61815094, -0.81693168, -0.30102424, -0.29030574],
       [ 0.8695976 ,  0.413755  ,  2.20047208,  0.17955692, -0.82159344],
       [ 0.59264235,  1.29869894, -1.18870241,  0.11590888, -0.09181687],
       [-0.96924265, -1.62888685, -2.05787102, -0.29705576,  0.68915542]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [23]:
np.random.randint(1,100)

55

* You want to return a particular number of random integers, specify the size as 3rd argument.

In [51]:
np.random.randint(1,100,10) # returns random integers between the limits

array([13, 64, 27, 63, 46, 68, 92, 10, 58, 24])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [24]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr

array([47, 14,  0, 26, 41,  2, 32,  1, 10,  3])

## Reshape
Returns an array containing the same data with a new shape. (basically representing the array using new dimensions)

In [27]:
arr # 1-D array of numbers

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
arr.reshape(5,5) # reshape() method transform the array into specified dimensions. Original array is as is, check below.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [29]:
ranarr

array([23, 12, 15, 29, 30, 15, 10, 25, 31, 46])

In [30]:
ranarr.max()

46

* You can get the index location of the max element or min element; using argmax() & argmin()

In [31]:
ranarr.argmax() # index of the max element in the array

9

In [32]:
ranarr.min()

10

In [33]:
ranarr.argmin() # index of min element in the array

6

## Shape

Shape is an attribute that arrays have (not a method):

In [34]:
# Vector
arr.shape   # shape is an attribute, not a method

(25,)

In [35]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [36]:
arr.reshape(1,25).shape

(1, 25)

In [37]:
arr.reshape(5,5).shape

(5, 5)

In [39]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [76]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [75]:
arr.dtype

dtype('int64')

# Great Job!